doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
            geonames:
                url: '%env(DATABASE_GEONAMES_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            geonames:
                connection: geonames
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    BordeuxGeoNameBundle:
                        is_bundle: true
                        type: annotation
                        dir: 'Entity'
                        prefix: 'Bordeux\Bundle\GeoNameBundle\Entity'
                        alias: GeoNames
    #orm:
    #    auto_generate_proxy_classes: true
    #    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    #    auto_mapping: true
    #    mappings:
    #        App:
    #            is_bundle: false
    #            type: annotation
    #            dir: '%kernel.project_dir%/src/Entity'
    #            prefix: 'App\Entity'
    #            alias: App
